name: Automatic Create Update Wpt PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: read

jobs:
  create-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Module
        run: npm i

      - name: Git Config
        shell: bash
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"

      - name: Install Wpt Update Utils
        shell: bash
        run: |
          npm install -g @node-core/utils
          ncu-config set --global username tsctx
          ncu-config set --global token ${{ secrets.FOREVER_PERSONAL_GITHUB_ACCESS_TOKEN }}

      - name: Check if PR exists
        id: check-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_title="chore(wpt): update wpt"
          
          ${{ github.event.repository.default_branch }}"
          echo "branch_name=$(gh pr list --state open -S "\\"${pr_title}\\" in:title" -B ${base_branch} -L 1 --jq ".[] | [.headRefName]" --json headRefName | jq '.[0]' | sed -e 's/"//g')" > "$GITHUB_OUTPUT"

      - name: Update Wpt
        shell: bash
        run: |
          npm run update:wpt

      - name: Check Update
        shell: bash
        id: check-update
        run: |
          echo "should_update_wpt=false" > "$GITHUB_OUTPUT"
          git add test/fixtures/wpt/*
          # origin/${{ github.event.repository.default_branch }}
          files=$(git diff HEAD --name-only)
          while IFS= read -r file; do
            if [[ $file == test/fixtures/wpt/* ]]; then
              echo "should_update_wpt=true" > "$GITHUB_OUTPUT"
            fi
          done <<< $files

      - name: Commit Patch
        if: ${{ steps.check-update.outputs.should_update_wpt == 'true' }}
        shell: bash
        id: commit-patch
        run: |
          branch="chore/update-wpt-$(date '+%Y-%m-%d-%H')"
          if ["${{ steps.check-pr.outputs.branch_name }}"]; then
            branch="${{ steps.check-pr.outputs.branch_name }}"
          fi
          git add test/fixtures/wpt/*
          git commit -m "chore(wpt): update wpt"
          git push -f origin "HEAD:$branch"
          echo "branch=$branch" > "$GITHUB_OUTPUT"

      - name: Create PR
        if: ${{ steps.check-update.outputs.should_update_wpt == 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
            const should_update_wpt = ${{ steps.check-update.outputs.should_update_wpt }};
            const hasPR = "${{ steps.check-pr.outputs.branch_name }}";
            if (should_update_wpt && !hasPR) {
                await github.rest.pulls.create({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    head: "${{ steps.commit-patch.outputs.branch }}",
                    base: "${{ github.event.repository.default_branch }}",
                    title: `chore(wpt): update wpt`,
                    body: ""
                });
            }
